sudo: required

language: ruby

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker-compose -f docker-compose.test.yml build --pull
  - docker-compose -f docker-compose.test.yml run engine rake db:test:prepare

script:
  - docker-compose -f docker-compose.test.yml run engine rspec spec

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build --pull --build-arg APP_ENV=production -t babili/engine:latest ./;
    docker push babili/engine:latest;
    else
    docker build --pull --build-arg APP_ENV=development -t babili/engine:release-candidate ./;
    docker push babili/engine:release-candidate;
    fi
