version: "2"

networks:
  main:
    driver: bridge

services:
  postgres-babili-test:
    image: postgres:13.6-alpine3.15
    networks:
      - main
    env_file: docker-compose.test.env

  babili-engine-test:
    build: .
    networks:
      - main
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres-babili-test
    env_file: docker-compose.test.env
