version: "2"

networks:
  main:
    driver: bridge

services:
  postgres:
    image: postgres:9.5
    networks:
      - main
    env_file: docker-compose.test.env

  engine:
    build: .
    networks:
      - main
    depends_on:
      - postgres
    env_file: docker-compose.test.env
